remote_theme: pmarsceill/just-the-docs
color_scheme: dark
last_edit_timestamp: true
last_edit_time_format: "%F at %R"

collections:
  guides:
    permalink: "/:collection/:slug"
    output: true
  accepted:
    permalink: "/:collection/:slug"
    output: true

just_the_docs:
  collections:
    guides:
      name: Guides
    rfcs:
      name: Accepted RFCs
