remote_theme: pmarsceill/just-the-docs
color_scheme: dark
last_edit_timestamp: true
last_edit_time_format: "%F at %R"

collections:
  rfcs:
    permalink: "/:path/"
    output: true

just_the_docs:
  collections:
    rfcs:
      name: RFCs
