remote_theme: pmarsceill/just-the-docs
color_scheme: dark
last_edit_timestamp: true
last_edit_time_format: "%F at %R"
search_enabled: false

collections:
  guides:
    permalink: "/:collection/:path"
    output: true
  accepted:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    guides:
      name: Guides
    accepted:
      name: Accepted RFCs
